### PR TITLE
Refs aurelia/bundler#92 - Attempting to fix jquery/bootstrap docs.

### PR DESCRIPTION
**Pull request by hozn**
I, I think like many others, struggled to get jquery and bootstrap fully imported into my aurelia app (started with contact-manager sample).  https://github.com/aurelia/bundler/issues/92 seemed to be the best answer, so I took a stab at tweaking the docs to reflect the solution that worked for me as proposed by @ERobishaw.

### CODE REVIEW

**Comment by mika76** [comment]
This caught me out too - it should be accepted asap

**Comment by mika76** [comment]
@EisenbergEffect can you not accept this change? 2 months is a long time for something already done - and I spent a long while figuring all this out as a Aurelia newbie...

**Comment by mika76** [comment]
@hozn You might want to make the change of version 2.2.4 of jquery *having* to be installed also. As per http://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/ you can use jquery 3 as well...

**Comment by AshleyGrant** [comment]
@mika76 I'll note that the solution @hozn implements in this PR isn't the *only* way to do this. I use a slightly simpler solution in my Aurelia demo app that I use when I speak at conferences.

Loading bootstrap (specifically its JS code) is a problem other module loader setups have. I've had to submit multiple PRs to the JSPM registry to fix how JSPM configures jQuery and Bootstrap, and even then it sometimes doesn't work. The problem is here: https://github.com/twbs/bootstrap/blob/v3.3.7/dist/js/bootstrap.js#L7

```javascript
if (typeof jQuery === 'undefined') {
  throw new Error('Bootstrap\'s JavaScript requires jQuery')
}
```

Bootstrap looks for jQuery to be available in the global namespace. I've linked to the latest version (3.3.7) above, but it's still the case even in the latest 4.0 alpha. B/c it's looking in the global namespace, things can get wonky. 

This is why I tell people to load bootstrap and jQuery from a CDN. It'll remove the pain of dealing with this issue, while simultaneously reducing bandwidth use for your users.

I don't personally have any reservations for accepting this PR, but it's not my personally preferred method of handling this. I'm sure other core team members might disagree with me, though.

**Comment by AshleyGrant** [comment]
Here is the solution I use in my demo app:
***aurelia.json***
```json
"jquery",
{
  "name": "bootstrap",
  "path": "../node_modules/bootstrap/dist",
  "main": "js/bootstrap.min",
  "deps": ["jquery"],
  "exports": "$",
  "resources": [
    "css/bootstrap.css"
  ]
}
```

***package.json***
```json
"bootstrap": "^3.3.7",
"jquery": "^3.1.0",
```

***app.js*** (or any js/ts file you need jQuery)

```javascript
import $ from 'bootstrap';

console.log('$ looks like', $);
```

What that code logs to the console:
image

I haven't really tested this solution extensively to, e.g. see if it works when using multiple jQuery plugins, but it works for the "just Bootstrap" use-case.

**Comment by hozn** [comment]
Yeah, I was just implementing the solution that others had proposed.  The docs definitely need to be updated, as the current documentation doesn't work (at least not completely) and I imagine that looking to use Bootstrap w/ Aurelia is pretty typical.  To be honest, even the solution I documented, while removing any errors, left me with bootstrap dropdowns (data-toggle=dropdown) that weren't getting wired up by bootstrap's JS.  I tried various import statements, but ended up prepending jquery and bootstrap so I could move on.  Obviously the CDN approach would work too.  It would be nice if the documentation provided full working instructions, though, including any additional steps (config, imports, etc.) to ensure that bootstrap js can wire up components in the views.

**Comment by EisenbergEffect** [comment]
@AshleyGrant Should this be merged? or do you think we need some other clarification here?

**Comment by mika76** [comment]
@EisenbergEffect from my points of view, the tutorial needs fixing up - it was my first crack at Aurelia and the tutorial does not work - so it's not a great intro. If this merge fixes it even a bit it's better than what's there currently...

**Comment by EisenbergEffect** [comment]
Ping @AshleyGrant

**Comment by EisenbergEffect** [comment]
Ping @AshleyGrant

**Comment by EisenbergEffect** [comment]
Ping @AshleyGrant

**Comment by geomorillo** [comment]
hello is 2018 is this already fixed? the tutorial is not loading bootstrap , since im a newbie im really disapointed this is not working should i move to anothe framework?

**Comment by AshleyGrant** [comment]
Which tutorial are you talking about? The one located at http://aurelia.io/docs/tutorials/creating-a-contact-manager gives full instructions on how to use Bootstrap and jQuery with the Aurelia CLI's default setup.

**Comment by geomorillo** [comment]
yes thats the one bootstrap is not loading correctly i did follow step by step and im pretty sure i did not make any mistakes. i see the cli console complaining about popper.js 


`------- File not found or not accessible ------
| Location: c:/Users/geomorillo/Desktop/code/contact-manager/popper.js
| Requested by: c:\Users\geomorillo\Desktop\code\contact-manager\node_modules\bootstrap\dist\js\bootstrap.min.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package
 -----------------------------------------------
 ------- File not found or not accessible ------
| Location: c:/Users/geomorillo/Desktop/code/contact-manager/popper.js
| Requested by: c:\Users\geomorillo\Desktop\code\contact-manager\node_modules\bootstrap\dist\js\bootstrap.min.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package
`

sure i understand that i have to include popper.js in aurelia.json as a dependency but the tutorial doesn't state anything at all, and i get a blank page
Also firefox console  shows some errors i think as a result of not finding this dep.

`unreachable code after return statement
[Saber más]
vendor-bundle.js:3599:4
Error en el mapeo fuente: request failed with status 404
URL del recurso: http://localhost:9000/scripts/vendor-bundle.js
URL del mapa fuente: bootstrap.min.js.map;define('bootstrap',
[Saber más]
Error: Script error for "main"
http://requirejs.org/docs/errors.html#scripterror
Stack trace:
Error: Script error for "main"
http://requirejs.org/docs/errors.html#scripterror
    makeError@http://localhost:9000/scripts/vendor-bundle.js:3956:17
    onScriptError@http://localhost:9000/scripts/vendor-bundle.js:5526:36
From previous event:
    DefaultLoader.prototype.loadModule@http://localhost:9000/scripts/vendor-bundle.js:23720:14
    config@http://localhost:9000/scripts/vendor-bundle.js:21497:14
    bootstrap/p<@http://localhost:9000/scripts/vendor-bundle.js:21533:14
From previous event:
    bootstrap@http://localhost:9000/scripts/vendor-bundle.js:21532:13
    run/<@http://localhost:9000/scripts/vendor-bundle.js:21519:9
From previous event:
    run@http://localhost:9000/scripts/vendor-bundle.js:21514:12
    @http://localhost:9000/scripts/vendor-bundle.js:21539:37
    execCb@http://localhost:9000/scripts/vendor-bundle.js:5484:24
    check@http://localhost:9000/scripts/vendor-bundle.js:4671:43
    enable@http://localhost:9000/scripts/vendor-bundle.js:4964:17
    enable@http://localhost:9000/scripts/vendor-bundle.js:5345:21
    enable/<@http://localhost:9000/scripts/vendor-bundle.js:4949:25
    bind/<@http://localhost:9000/scripts/vendor-bundle.js:3922:20
    each@http://localhost:9000/scripts/vendor-bundle.js:3847:31
    enable@http://localhost:9000/scripts/vendor-bundle.js:4901:17
    init@http://localhost:9000/scripts/vendor-bundle.js:4576:21
    localRequire/<@http://localhost:9000/scripts/vendor-bundle.js:5248:25
vendor-bundle.js:3414:16
Ha fallado la carga del <script> con origen "http://localhost:9000/src/main.js".
localhost:9000:1
`

so i did install it using the command  npm install popper.js --save and included its deps on aurelia.json
`        "dependencies": [
            "jquery",
            {
     "name": "popper.js",
     "path": "../node_modules/popper.js/dist/umd",
     "main": "popper.min"
   },
      {
        "name": "bootstrap",
        "path": "../node_modules/bootstrap/dist",
        "main": "js/bootstrap.min",
        "deps": ["jquery"],
        "exports": "$",
        "resources": [
          "css/bootstrap.css"
        ]
      }`


No errors on cli but still a blank page,  the firefox console again 

`Unhandled rejection Error: Load timeout for modules: app
http://requirejs.org/docs/errors.html#timeout
    makeError@http://localhost:9000/scripts/vendor-bundle.js:3956:17
    checkLoaded@http://localhost:9000/scripts/vendor-bundle.js:4486:23
    checkLoaded/checkLoadedTimeoutId<@http://localhost:9000/scripts/vendor-bundle.js:4507:25
From previous event:
    DefaultLoader.prototype.loadModule@http://localhost:9000/scripts/vendor-bundle.js:23722:14
    importViewModelResource@http://localhost:9000/scripts/vendor-bundle.js:32012:14
    ensureViewModel@http://localhost:9000/scripts/vendor-bundle.js:33332:16
    createController@http://localhost:9000/scripts/vendor-bundle.js:33308:14
    _createControllerAndSwap@http://localhost:9000/scripts/vendor-bundle.js:33283:14
    compose@http://localhost:9000/scripts/vendor-bundle.js:33369:16
    compose@http://localhost:9000/scripts/vendor-bundle.js:33632:14
    setRoot@http://localhost:9000/scripts/vendor-bundle.js:22675:14
    configure/<@http://localhost:9000/scripts/app-bundle.js:40:14
From previous event:
    configure@http://localhost:9000/scripts/app-bundle.js:39:5
    config/<@http://localhost:9000/scripts/vendor-bundle.js:21504:16
From previous event:
    config@http://localhost:9000/scripts/vendor-bundle.js:21499:14
    bootstrap/p<@http://localhost:9000/scripts/vendor-bundle.js:21535:14
From previous event:
    bootstrap@http://localhost:9000/scripts/vendor-bundle.js:21534:13
    run/<@http://localhost:9000/scripts/vendor-bundle.js:21521:9
From previous event:
    run@http://localhost:9000/scripts/vendor-bundle.js:21516:12
    @http://localhost:9000/scripts/vendor-bundle.js:21541:37
    execCb@http://localhost:9000/scripts/vendor-bundle.js:5484:24
    check@http://localhost:9000/scripts/vendor-bundle.js:4671:43
    enable@http://localhost:9000/scripts/vendor-bundle.js:4964:17
    enable@http://localhost:9000/scripts/vendor-bundle.js:5345:21
    enable/<@http://localhost:9000/scripts/vendor-bundle.js:4949:25
    bind/<@http://localhost:9000/scripts/vendor-bundle.js:3922:20
    each@http://localhost:9000/scripts/vendor-bundle.js:3847:31
    enable@http://localhost:9000/scripts/vendor-bundle.js:4901:17
    init@http://localhost:9000/scripts/vendor-bundle.js:4576:21
    localRequire/<@http://localhost:9000/scripts/vendor-bundle.js:5248:25
vendor-bundle.js:1398:13
`
so im out of ideas ....

**Comment by geomorillo** [comment]
yes thats the one i already redone it 4 times and not working please review it if its working or not thanks

**Pull request merged**
