### PR TITLE
Whitespace fixes

### PR DESCRIPTION
**Pull request by perlun**
(First, thanks for an absolutely great framework @EisenbergEffect (and all the rest of you). Very much appreciated - I was actually thinking if I might have to roll my own just to get _something_ that plays decently well with TypeScript, but after trying it out now for half an hour, I must say that the initial impression is _great_. It feels much more modern than some of the competing, older frameworks.)

Went through the "todo" guide first, and now wandering through the "contact manager" one, I noted some irregularities in the formatting, so here goes - my very first (but hopefully not last 😄) contribution to the project. (I assume that it's this example that is mis-formatted, since the others use the "whitespace-before-curly" syntax.)

### CODE REVIEW

**Comment by AshleyGrant** [comment]
@eisenbergeffect I'd say this is de minimus or whatever the term is that we don't need a signed CLA.

**Comment by perlun** [comment]
@AshleyGrant No worries, I signed it now as well. 😇

**Comment by perlun** [comment]
There you go @AshleyGrant and @EisenbergEffect - I found a bunch more so this PR grew, I did a few more commits but squashed them all eventually into one. Should take care of all "space after brace" issues in that file now.

**Comment by jdanyow** [comment]
Thanks @perlun

**Pull request merged**
