### PR TITLE
Update contact-manager-tutorial.md

### PR DESCRIPTION
**Pull request by madrus**
My message to Rob:
Hi Rob,
I have found a couple of typos (not so important but maybe nice to fix).
Also, I have seen some differences in the use of 'this' prefix in 'contact-detail' files.
I am not 100% sure that the proposed change is correct, but it works on my machine. :)
Feel free to accepts some or even none of the changes.
I have fallen in love with your Aurelia but I have yet too far to go.
Maybe these minor changes will prove to be useful.
Best regards,
Andre

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@madrus  **Thank you for contributing this pull request!** We're truly excited and honored to have you as a member of our community. We look forward to working together with you to further build the Aurelia platform.

We noticed that you haven't yet signed our CLA. We would appreciate it if you would consider doing that for us. Before signing, please take a few minutes to read [our contributing guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md). These guidelines will help get you up to speed on how our community likes to operate and how the pull request process works. Once you have read that, assuming you are in agreement, simply [sign our online CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1).

After you've signed, please ping this issue to let us know and we'll get your improvements merged in.

Thank you again!
The Aurelia Team

**Comment by madrus** [comment]
Hi The Aurelia Team,
I have signed the agreement but I am afraid I don't know the "pinging" the issue exactly means.Please send me a git command or a link where I can read about it.I have not found anything about it in the Contributing Guidelines.
Regards,Andre Roussakoff


Date: Thu, 25 Aug 2016 17:27:37 -0700

**Comment by EisenbergEffect** [comment]
We just mint to drop a comment on the issue to let us know. You have succeeded :)

**Comment by madrus** [comment]
😊

Verzonden met mijn Windows Phone
________________________________
От: Rob Eisenberg<mailto:notifications@github.com>
Отправлено: ‎29.‎08.‎2016 17:45
Кому: aurelia/framework<mailto:framework@noreply.github.com>
Копия: Andre Roussakoff<mailto:madrusnl@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Тема: Re: [aurelia/framework] Update contact-manager-tutorial.md (#524)

We just mint to drop a comment on the issue to let us know. You have succeeded :)

**Comment by EisenbergEffect** [comment]
Thanks!

**Pull request merged**
