### PR TITLE
doc(polymer): Remove polymer docs

### PR DESCRIPTION
**Pull request by davismj**
The author of the docs has abandoned this library and it seems that the documentation is no longer working or relevant.

Thanks to @HIRANO-Satoshi for this suggestion.

### CODE REVIEW

**Comment by Alexander-Taran** [comment]
Need some delibiration?
or can be merged?

**Comment by EisenbergEffect** [comment]
@davismj Can you remove `api.json` from the PR? I can merge then.
It would be great to have an updated article that works with Polymer 2.x. Or maybe an article just talking about using Aurelia with vanilla WebComponents.

**Comment by davismj** [comment]
@EisenbergEffect done

**Comment by bigopon** [comment]
We have moved the docs.

**Pull request closed without merging**
