### PR TITLE
doc(aurelia-cli): add docs for revisions and bundling

### PR DESCRIPTION
**Pull request by AStoker**
Covers features added:
https://github.com/aurelia/cli/pull/326
https://github.com/aurelia/cli/pull/305

### CODE REVIEW

**Comment by AStoker** [comment]
@EisenbergEffect, could we get this merged and published please, since they go hand in hand with the update to the CLI and build revisions?

**Comment by EisenbergEffect** [comment]
Oops! Dang...I just released everything and pushed the docs data update....

**Comment by EisenbergEffect** [comment]
This may have to wait a bit longer...maybe until tomorrow.

**Comment by AStoker** [comment]
That's not a problem. Just had a guy on Gitter asking about build revisions, and couldn't point him to the docs regarding it's setup 😄

**Comment by EisenbergEffect** [comment]
I've merged it so you can point him to the actual md file on Github. We'll get it out to the official site soon.

**Comment by AStoker** [comment]
Awesome, thanks!

**Pull request merged**
