### PR TITLE
chore: add task 'cover' to run tests with code coverage

### PR DESCRIPTION
**Pull request by 4kochi**
Signed CLA as Andreas Krummsdorf

You also might be interested in https://github.com/litixsoft/karma-detect-browsers, which allows you to run the karma tests in all browser of the current system. But thats another topic :-)

Additionally, i wonder you are using some kind of CI System? I found https://travis-ci.org very useful for open source projects. It's really easy to integrate and it will run the tests on every commit/pull-request.

### CODE REVIEW

**Comment by zewa666** [comment]
What code coverage tool is used for this one? Istanbul? Nice idea :+1: 
@AshleyGrant is doing some work with Travis-CI as far as I know

**Comment by 4kochi** [comment]
It uses karma-coverage which uses istanbul under the hood

**Comment by EisenbergEffect** [comment]
Yep, we are getting the CI in place. I'm waiting for a todo list from @AshleyGrant to get him what he needs to finish the setup.

@4kochi This looks cool. I'll test it out and see about the merge shortly. Thanks!

**Comment by 4kochi** [comment]
Your welcome. Actually you are all really fast here answering to the issues. Great to see.

**Pull request merged**
