### PR TITLE
doc(integrating-with-polymer): add additional bower instructions

### PR DESCRIPTION
**Pull request by ebekker**

### CODE REVIEW

**Comment by AshleyGrant** [comment]
@ebekker please update your commit message so that it follows our [commit message guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit). I would recommend `doc(polymer): add additional bower instructions` 

Thanks!

**Comment by ebekker** [comment]
My mistake, I'll correct it shortly

**Comment by AshleyGrant** [comment]
Thanks! Also, if you have not signed our CLA, please sign it [here](http://goo.gl/forms/dI8QDDSyKR). We'll review the updates shortly.

**Comment by ebekker** [comment]
Just signed the CLA after I saw it mentioned in the guidelines.

**Comment by ebekker** [comment]
I've recreated a second patch and PR with the corrected comment format.  I used your suggestion with a slight modification in the _scope_ which I renamed to match the most recent commit against this same article for consistency.

**Pull request closed without merging**
