### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by nomack84**
Fix a long time typo...

Edit: fix a typo in a typo PR, amazing... hahaha

### CODE REVIEW

**Comment by nomack84** [comment]
I've signed the CLA already ;)

**Comment by AshleyGrant** [comment]
Unfortunately, you made a typo in your comment. I think that cancels out fixing the typo in the docs :-P

**Comment by nomack84** [comment]
@AshleyGrant oh yeah :joy:

**Comment by EisenbergEffect** [comment]
Thanks!

**Pull request merged**
