### PR TITLE
Update contact-manager-tutorial.md

### PR DESCRIPTION
**Pull request by RGravesDev**
The heading name should be 'contact-list.html'.

### CODE REVIEW

**Comment by soulchainer** [comment]
Dup of #497

**Comment by RGravesDev** [comment]
I believe I need to close the pull request, so that's what I did. Feel free to message me if I need to delete the 'RGravesDev:patch-2' branch too, so I can learn the right git PR procedures.

**Comment by soulchainer** [comment]
**Note**: I have no relationship with the project. I just trying to learn Aurelia and just was proposing a PR (because I'm reading the tutorials) and looked quickly the rest of PR just in case there was collisions and there wasn't any (well, one, I just keep that part of the code out of my PR and quoted that PR, for allow them to merge that PR if they want ;)), but I spot so many dups and I feel like I should try to ease things to maintainers ;). Greetings, @RGravesDev.
Before proposing a PR is a good practice to [read the guidelines about contributing](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

**Comment by RGravesDev** [comment]
Excellent. Thanks @soulchainer for the link to the guidelines.

**Pull request closed without merging**
