### PR TITLE
doc(all): update usage of polymer/mutationobservers to webcomponents

### PR DESCRIPTION
**Pull request by Vheissu**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Oh...we don't want that actually. We don't want them to have to load all of web components just to get the mutation observer polyfill. We will need to research this and see if we can find another polyfill that is just mutation observers. Is it possible that they have it as standalone in the webcomponents project?

**Comment by schatekar** [comment]
@EisenbergEffect  If you do find an polyfill that is just mutation observers, that will we be able to run Aurelia apps on PhantomJs 1.x? Currently lack of mutation observers is preventing me from running my app on PhantomJs 1.x

**Comment by EisenbergEffect** [comment]
It's still available as a standalone here: https://github.com/webcomponents/webcomponentsjs/blob/master/src/MutationObserver/MutationObserver.js
So, we need to update the docs to show how to include just that.

**Comment by EisenbergEffect** [comment]
@Vheissu Can you check in on updating the import to instead import only the mutation observer polyfill rather than the entire web components polyfill?

**Comment by Vheissu** [comment]
@EisenbergEffect Absolutely. I'll sort this out asap.

**Comment by Vheissu** [comment]
@EisenbergEffect I have ammended the commit to only include the MutationObserver polyfill component of webcomponents. It also takes care of the WeakMap polyfill as well.

**Comment by EisenbergEffect** [comment]
Awesome. Merged. Thanks!

**Pull request merged**
