### PR TITLE
chore(eslint): update to eslint 2

### PR DESCRIPTION
**Pull request by AshleyGrant**
Renamed `.eslintrc` to `.eslintrc.json`
Updated reference to point to `.eslintrc.json` in `aurelia-tools`
Updated package.json to point to packages needed for eslint 2.
Added `eslint@^2.10.2` as an explicit dependency to make sure that linting with `babel-eslint` will work as there is a bug in `2.10.0` and `2.10.1`.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Does this properly handle decorators and class instance fields as well?

**Comment by AshleyGrant** [comment]
This is the output when I run `gulp lint` 

```bash
Ashley@Desktop MINGW64 ~/github/ashleygrant/framework (update_eslint)                      
$ gulp lint                                                                                
[10:27:05] Using gulpfile ~\github\ashleygrant\framework\gulpfile.js                       
[10:27:05] Starting 'lint'...                                                              
[10:27:06] 'lint' errored after 553 ms                                                     
[10:27:06] ESLintError in plugin 'gulp-eslint'                                             
Message:                                                                                   
    Expected to return a value at the end of this function.                                
Details:                                                                                   
    fileName: C:\Users\Ashley\github\ashleygrant\framework\src\framework-configuration.js  
    lineNumber: 37                                                                         
[10:27:06]                                                                                 
C:\Users\Ashley\github\ashleygrant\framework\src\framework-configuration.js                
   37:47  error  Expected to return a value at the end of this function  consistent-return 
  101:10  error  Expected to return a value at the end of this function  consistent-return 
                                                                                           
✖ 2 problems (2 errors, 0 warnings)                                                        
```

So yes, it handles decorators and class instance fields. And is producing an error as expected for the code that breaks the `consistent-return` linting rule.

**Comment by AshleyGrant** [comment]
Note that I've cheated and inserted the `.eslintrc.json` file in my `aurelia-tools` PR directly in to the `node_modules\aurelia-tools` folder. This PR won't work properly until `aurelia-tools` is updated and the `package.json` is updated to the new `aurelia-tools` release.

**Comment by EisenbergEffect** [comment]
I don't see any decorator usage in framework. It does use the instance fields, so I imagine if it's handling that it is getting the other...though I'm not sure how it picks up the settings.

**Comment by AshleyGrant** [comment]
That's a good point. I'll add a decorator usage and test.

**Pull request merged**
