### PR TITLE
doc(getting-help): fix typos

### PR DESCRIPTION
**Pull request by ScottWhittaker**

### CODE REVIEW

**Comment by AshleyGrant** [comment]
Scott, would you mind amending your commit message to match our [commit message guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit). I recommend `doc(getting-help): fix typos`

Thanks!

**Comment by ScottWhittaker** [comment]
Hi Ashley, commit message amended - took me a while to figure it out!

**Comment by EisenbergEffect** [comment]
Thanks! BTW, @ScottWhittaker you are contributor 400 :)

**Comment by AshleyGrant** [comment]
@ScottWhittaker thanks for figuring out how to amend the title! The first time you learn about amending a commit and force pushing, is fun. Just wait till I ask you to rebase :-) I had to write a blog post so I could remember how to do it.

Congrats on being contributor 400!

**Pull request merged**
