### PR TITLE
style(aurelia): remove redundant variables

### PR DESCRIPTION
**Pull request by Gheoan**

### CODE REVIEW

**Comment by atsu85** [comment]
What is the expected benefit of these inlining changes? I'd say the original code is slightly easier to read, the result of the change is slightly smaller js file, but don't know if it matters much after the minification.

**Comment by Gheoan** [comment]
I think inlining variable value makes the code easier to understand and change. For example:
```js
      let evt = DOM.createCustomEvent('aurelia-started', { bubbles: true, cancelable: true });
      DOM.dispatchEvent(evt);
```
Let's pretend a developer decides that the `aurelia-started` event should not fire. The developer goes ahead and removes the `dispatchEvent` call.
```js
      let evt = DOM.createCustomEvent('aurelia-started', { bubbles: true, cancelable: true });
```
Now, because declarations are hoisted the developer has to check the whole scope for references to the `evt` variable and then remove it.
Inlining the variable value makes it clear that the value has no other use.
The size is indeed unchanged because of minification.

**Comment by jdanyow** [comment]
closing- less readable, try to stick to around 80 characters line length.

**Comment by Gheoan** [comment]
@jdanyow should a rule that would enforce a maximum line length of 80 be added to the linting tool?

**Pull request closed without merging**
