### PR TITLE
(doc) Source code listing updated.

### PR DESCRIPTION
**Pull request by abhilashsajeev**
Earlier version was not showing the first line of code snippets

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I'm unable to reproduce any issues. I don't see any missing code when I view the site...Can you provide some more information on this?

**Comment by abhilashsajeev** [comment]
May be you should view it in github read me mode.

example

Similer problem occurs in the readme files.

**Comment by EisenbergEffect** [comment]
Is there some reason that you aren't reading them in the docs?

**Comment by abhilashsajeev** [comment]
Well not actually. Yesterday the docs section of the web was broken. So I used the markdowns here for reference and saw this.

**Comment by EisenbergEffect** [comment]
I'm going to close this for now.Thank you though!

**Pull request closed without merging**
