### PR TITLE
Italian translation 1st step

### PR DESCRIPTION
**Pull request by Akelitz**

### CODE REVIEW

**Comment by AshleyGrant** [comment]
Thanks for the help getting the Italian translation started! We're going to need you to update your commit messages to match the commit message guidelines in our contributor's guide. https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit

Thanks!

**Comment by EisenbergEffect** [comment]
@Akelitz **Thank you for contributing this pull request!** We're truly excited and honored to have you as a member of our community. We look forward to working together with you to further build the Aurelia platform.

We noticed that you haven't yet signed our CLA. We would appreciate it if you would consider doing that for us. Before signing, please take a few minutes to read [our contributing guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md). These guidelines will help get you up to speed on how our community likes to operate and how the pull request process works. Once you have read that, assuming you are in agreement, simply [sign our online CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1).

After you've signed, please ping this issue to let us know and we'll get your improvements merged in.

Thank you again!
The Aurelia Team

**Comment by EisenbergEffect** [comment]
Closing since there's no CLA sig after a long time.

**Comment by Akelitz** [comment]
Sorry @AshleyGrant and @EisenbergEffect but I totally missed your communication about this pull request (I am still a rookie on GitHub) till now.
I have signed the CLA now, but maybe it is too late, so please tell me if (and how) I can re-submit this PR.

**Comment by AshleyGrant** [comment]
You can definitely resubmit it. I would re-base off of the current master branch and make any updates necessary to the content, as the English docs have likely changed since you originally submitted this PR. Once you do that, you can create a new PR and we'll make sure everything is good and we'll get it merged!

**Pull request closed without merging**
